### ISSUE TITLE
Invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by DimitrijeManic** [spacelift-io/spacelift-helm-charts#60] opened 2024-06-19 14:52 UTC
Hi there, I am running into the following error when attempting to deploy the operator using versions 0.19.0, & 0.20.0.
version 0.18.0 works without issues.

```
{"level":"info","ts":"2024-06-19T14:40:39Z","msg":"Worker pool successfully registered.","controller":"workerpool","controllerGroup":"workers.spacelift.io","controllerKind":"WorkerPool","WorkerPool":{"name":"workers","namespace":"spacelift"},"namespace":"spacelift","name":"workers","reconcileID":"8a55cbc6-cb8a-4280-920a-78b67db0e17b"}
{"level":"info","ts":"2024-06-19T14:40:39Z","logger":"KubeAPIWarningLogger","msg":"unknown field \"status.desiredPoolSize\""}
{"level":"info","ts":"2024-06-19T14:40:39Z","msg":"Observed a panic in reconciler: runtime error: invalid memory address or nil pointer dereference","controller":"workerpool","controllerGroup":"workers.spacelift.io","controllerKind":"WorkerPool","WorkerPool":{"name":"workers","namespace":"spacelift"},"namespace":"spacelift","name":"workers","reconcileID":"8a55cbc6-cb8a-4280-920a-78b67db0e17b"}
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1532306]
goroutine 165 [running]:
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile.func1()
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.0/pkg/internal/controller/controller.go:116 +0x1e5
panic({0x169b720?, 0x2729ab0?})
	/opt/hostedtoolcache/go/1.21.3/x64/src/runtime/panic.go:914 +0x21f
github.com/spacelift-io/kube-workerpool-controller/internal/controller.(*WorkerPoolReconciler).handlePoolSizeChange(0xc000596ac0, {0x1b1ae10, 0xc0003ef050}, 0xc00084a000, {{{0x0, 0x0}, {0x0, 0x0}}, {{0x0, 0x0}, ...}, ...})
	/home/runner/work/kube-workerpool-controller/kube-workerpool-controller/internal/controller/workerpool_controller.go:160 +0x86
github.com/spacelift-io/kube-workerpool-controller/internal/controller.(*WorkerPoolReconciler).Reconcile(0xc000596ac0, {0x1b1ae10, 0xc0003ef050}, {{{0xc00069a200?, 0x5?}, {0xc00069a1f6?, 0xc000841d48?}}})
	/home/runner/work/kube-workerpool-controller/kube-workerpool-controller/internal/controller/workerpool_controller.go:147 +0x7f8
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0x1b1dca8?, {0x1b1ae10?, 0xc0003ef050?}, {{{0xc00069a200?, 0xb?}, {0xc00069a1f6?, 0x0?}}})
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.0/pkg/internal/controller/controller.go:119 +0xb7
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0003d32c0, {0x1b1ae48, 0xc0000c8550}, {0x1717860?, 0xc000594020?})
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.0/pkg/internal/controller/controller.go:316 +0x3c5
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0003d32c0, {0x1b1ae48, 0xc0000c8550})
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.0/pkg/internal/controller/controller.go:266 +0x1c9
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.0/pkg/internal/controller/controller.go:227 +0x79
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2 in goroutine 99
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.0/pkg/internal/controller/controller.go:223 +0x565

```

When viewing the `WorkerPool` CRD the status only contains `actualPoolSize` which might be the culprit?

**Comment by markshawtoronto** [comment] 2024-08-16 18:44
I have the same problem, trying to upgrade from 0.18 to anything between 0.19 - 0.24 for helm chart `spacelift-workerpool-controller`. 
Is there a recommended workaround?

**Comment by eliecharra** [comment] 2024-08-19 07:44
Hey there 👋🏻

Sorry for the delay 🙇🏻 

The panic here is not the root cause, but more of a consequence of the first problem, which is 

```
{"level":"info","ts":"2024-06-19T14:40:39Z","logger":"KubeAPIWarningLogger","msg":"unknown field \"status.desiredPoolSize\""}
```

I think the CRD in the cluster is not up to date. If you are using Helm version > 3 it should be [done for you](https://helm.sh/docs/chart_best_practices/custom_resource_definitions/#install-a-crd-declaration-before-using-the-resource)
If you are using an old version of Helm, please make sure CRDs are installed first 🙏🏻

**Comment by eliecharra** [comment] 2024-08-19 07:45
Can your guys check the spec of the CRD installed in the cluster, it should contain this [field](https://github.com/spacelift-io/spacelift-helm-charts/blob/main/spacelift-workerpool-controller/crds/workerpool-crd.yaml#L4639) in the status section

**Comment by markshawtoronto** [comment] 2024-08-19 18:33
@eliecharra 🤔 I got it working but it required these steps:

1. Delete the helm chart and WorkerPool:
```
# resource "helm_release" "spacelift_worker_pool_controller" { version = "0.18.0" }
# resource "kubernetes_manifest" "spacelift_workerpool" { ... }
terraform apply
```

2. Manually delete the CRD:
```
kubectl delete crd workerpools.workers.spacelift.io 
```

3. Reinstall the helm chart and WorkerPool on a newer version so the helm chart recreates the CRD:
```
resource "helm_release" "spacelift_worker_pool_controller" { version = "0.19.0" }
resource "kubernetes_manifest" "spacelift_workerpool" { ... }
terraform apply
```

---
This is probably because of helm 3 limits from these docs:
```
There is no support at this time for upgrading or deleting CRDs using Helm.
This was an explicit decision after much community discussion due to the danger for unintentional data loss. Furthermore, there is currently no community consensus around how to handle CRDs and their lifecycle.
```

Probably there needs to be some documentation for upgrading to 0.19.0+ in the README or changelogs or both, and then a decision to avoid CRD changes or make it clear how to upgrade when there is one.

**Comment by akmal-spacelift** [comment] 2024-08-19 18:49
Thanks Mark!  I've just added the warning here as a pr to the docs:
https://github.com/spacelift-io/user-documentation/pull/588

Once it's reviewed it should be added to the documentation

**Comment by eliecharra** [comment] 2024-08-20 08:39
Ha indeed good catch @markshawtoronto , makes sense to add a warning in the docs then, thanks a lot @akmal-spacelift LGTM 🙏🏻

**Comment by eliecharra** [comment] 2024-08-23 12:47
I'm closing this one, hopefully the warning in the doc will help.

**Closed by eliecharra** 2024-08-23 12:47 UTC
